project:
  type: website

execute:
  freeze: auto

website:
  title: "Pyspatialml: machine learning for raster datasets"
  description: "Pyspatialml is a Python package for applying scikit-learn machine learning models to raster-based datasets"
  repo-url: https://github.com/stevenpawlely/pyspatialml
  page-navigation: true

  navbar:
      title: false
      background: primary
      search: true
      logo: docs/icon.png
      logo-alt: Pyspatialml
      logo-href: index.qmd
      tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/stevenpawley/Pyspatialml/tree/master/docs
          - text: Report a Bug
            href: https://github.com/stevenpawley/Pyspatialml/issues

      left:
        - text: Getting started
          href: docs/index.qmd
                        
        - text: Guide
          file: docs/quickstart.qmd
                
        - text: Reference
          file: reference/Raster.qmd
  
        - text: Tutorials
          file: docs/landcover.qmd

  sidebar:
    - title: "Home"
      style: "docked"
      contents:
        - section: "Pyspatialml"
          contents:
            - docs/index.qmd
            - docs/installation.qmd
            - docs/design.qmd
    
    - title: "Guide"
      style: "docked"
      contents:
        - section: "Geoprocessing"
          contents:
            - docs/quickstart.qmd
            - docs/geoprocessing.qmd
            - docs/plotting.qmd
            - docs/sampling.qmd
            - docs/transformers.qmd
    
    - title: "Tutorials"
      style: "docked"
      contents:
        - section: "Machine learning examples"
          contents:
            - docs/landcover.qmd
            - docs/multitarget-regression-soil-properties.qmd
            - docs/spatial-features.qmd

theme:
  light: spacelab
  dark: darkly

metadata-files:
  - _sidebar.yml

format:
  html:
    toc: true

quartodoc:
  package: pyspatialml
  sidebar: "_sidebar.yml"
  sections:
    - title: Raster datasets
      desc: "Raster is a class for reading and writing raster datasets"
      options:
        children: embedded

      contents:
        - Raster
        - RasterLayer

    - title: Vector tools
      desc: "Tools for working with vector datasets"
      options:
        children: embedded
      
      contents:
        - vector
    
    - title: Preprocessing
      desc: "Preprocessing tools for raster datasets"
      options:
        children: embedded
      
      contents:
        - preprocessing
