quartodoc:
  package: pyspatialml
  sections:
    - title: Raster datasets
      desc: "Raster is a class for reading and writing raster datasets"
      options:
        children: embedded
      contents:
        - Raster
        - RasterLayer

    - title: Vector tools
      desc: "Tools for working with vector datasets"
      options:
        children: embedded
      contents:
        - vector
    
    - title: Preprocessing
      desc: "Preprocessing tools for raster datasets"
      options:
        children: embedded
      contents:
        - preprocessing

project:
  type: website

execute:
  freeze: auto

website:
  title: "Pyspatialml: machine learning for raster datasets"
  description: "Pyspatialml is a Python package for applying scikit-learn machine learning models to raster-based datasets"
  repo-url: https://github.com/stevenpawlely/pyspatialml
  page-navigation: true

  navbar:
      title: false
      background: primary
      search: true
      tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/stevenpawley/Pyspatialml/tree/master/docs
          - text: Report a Bug
            href: https://github.com/stevenpawley/Pyspatialml/issues

      left:
        - text: "Getting started"
          href: index.qmd
                        
        - text: "Guide"
          file: docs/quickstart.qmd
                
        - text: "Reference"
          file: reference/Raster.qmd
  
        - text: "Tutorials"
          file: docs/landcover.qmd

  sidebar:
    - title: "Getting started"
      style: "docked"
      contents:
        - docs/index.qmd
        - docs/installation.qmd
        - docs/usage.qmd
    
    - title: "Guide"
      style: "docked"
      contents:
        - section: "Geoprocessing"
          contents:
            - docs/quickstart.qmd
            - docs/geoprocessing.qmd
            - docs/plotting.qmd
            - docs/sampling.qmd
            - docs/transformers.qmd
    
    - title: "Tutorials"
      style: "docked"
      contents:
        - section: "Landcover"
          contents:
            - docs/landcover.qmd

        - section: "Multitarget regression"
          contents:
            - docs/multitarget-regression-soil-properties.qmd
        
        - section: "Spatial feature engineering"
          contents:
            - docs/spatial-features.qmd
    
    - title: "Reference"
      style: "docked"
      contents:
        - section: Raster datasets
          contents:
            - reference/Raster.qmd
            - reference/RasterLayer.qmd

        - section: Vector tools 
          contents:
            - reference/vector.qmd
      
        - section: Preprocessing
          contents:
            - reference/preprocessing.qmd

theme:
  light: spacelab
  dark: darkly

format:
  html:
    toc: true
